# Generated by Django 5.0.14 on 2026-07-11 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('rubro', models.CharField(blank=True, choices=[('restaurante', 'Restaurantes'), ('super', 'Súper'), ('farmacia', 'Farmacia'), ('postres', 'Postres'), ('licores', 'Licores'), ('mascotas', 'Mascotas')], max_length=50, null=True, verbose_name='Rubro de Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('destacado', models.BooleanField(default=False)),
                ('rubro', models.CharField(choices=[('restaurante', 'Restaurantes'), ('super', 'Súper'), ('farmacia', 'Farmacia'), ('postres', 'Postres'), ('licores', 'Licores'), ('mascotas', 'Mascotas')], default='restaurante', max_length=50, verbose_name='Rubro de Negocio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='negocios/', verbose_name='Imagen de Portada')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo del Local')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descuento_porcentaje', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sede Principal', max_length=150, verbose_name='Nombre de la Sede')),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('abierto', models.BooleanField(default=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('hora_apertura', models.TimeField(blank=True, null=True)),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Costo de Envío')),
                ('estado', models.BooleanField(default=True, verbose_name='Sede Activa')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(default=5)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
