# Generated by Django 5.0.14 on 2026-05-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
    ]
