# Generated by Django 5.0.14 on 2026-07-11 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='propietario',
            field=models.OneToOneField(limit_choices_to={'rol': 'negocio'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.categoria'),
        ),
        migrations.AddField(
            model_name='sede',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='catalogo.negocio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='catalogo.sede'),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='catalogo.sede'),
        ),
    ]
