# Generated by Django 5.0.14 on 2026-07-16 08:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_categoria_activo_categoria_actualizado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valoracion',
            unique_together={('sede', 'cliente')},
        ),
    ]
