# Generated by Django 5.0.14 on 2026-07-11 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Repartidor'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_sede', to='catalogo.sede', verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_pedido', to='pedidos.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together={('pedido', 'producto')},
        ),
    ]
