# Generated by Django 5.2 on 2026-07-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo contra entrega'), ('pos', 'Tarjeta con POS contra entrega'), ('qr', 'Pago con Código QR (En línea)'), ('tarjeta', 'Pago con Tarjeta (En línea)')], default='efectivo', max_length=20, verbose_name='Método de pago'),
        ),
    ]
