# Generated by Django 5.0.14 on 2026-05-18 03:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True, verbose_name='Asignacion activa')),
                ('asignado_en', models.DateTimeField(auto_now_add=True, verbose_name='Asignado en')),
                ('recogido_en', models.DateTimeField(blank=True, null=True, verbose_name='Recogido en')),
                ('entregado_en', models.DateTimeField(blank=True, null=True, verbose_name='Entregado en')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_logistica', to='pedidos.pedido', verbose_name='Pedido')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_logistica', to=settings.AUTH_USER_MODEL, verbose_name='Repartidor')),
            ],
            options={
                'verbose_name': 'Asignacion de pedido',
                'verbose_name_plural': 'Asignaciones de pedidos',
                'ordering': ['-asignado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('asignado', 'Asignado'), ('recogido', 'Recogido'), ('entregado', 'Entregado')], max_length=20, verbose_name='Evento')),
                ('observacion', models.TextField(blank=True, verbose_name='Observacion')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_logistico', to='pedidos.pedido', verbose_name='Pedido')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_entregas', to=settings.AUTH_USER_MODEL, verbose_name='Repartidor')),
            ],
            options={
                'verbose_name': 'Historial de entrega',
                'verbose_name_plural': 'Historiales de entrega',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PerfilRepartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_actual', models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En ruta'), ('inactivo', 'Inactivo')], default='disponible', max_length=20, verbose_name='Estado actual')),
                ('vehiculo', models.CharField(blank=True, max_length=100, verbose_name='Vehiculo')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('ultima_actualizacion_ubicacion', models.DateTimeField(blank=True, null=True, verbose_name='Ultima actualizacion de ubicacion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_repartidor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de repartidor',
                'verbose_name_plural': 'Perfiles de repartidor',
                'ordering': ['usuario__username'],
            },
        ),
        migrations.AddConstraint(
            model_name='asignacionpedido',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('repartidor',), name='unique_active_assignment_per_driver'),
        ),
    ]
