# Generated by Django 5.0.14 on 2026-07-11 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistica', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionpedido',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_logistica', to='pedidos.pedido', verbose_name='Pedido'),
        ),
    ]
