# Generated by Django 5.0.14 on 2026-07-11 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistica', '0002_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionpedido',
            name='repartidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_logistica', to=settings.AUTH_USER_MODEL, verbose_name='Repartidor'),
        ),
        migrations.AddField(
            model_name='historialentrega',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_logistico', to='pedidos.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='historialentrega',
            name='repartidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_entregas', to=settings.AUTH_USER_MODEL, verbose_name='Repartidor'),
        ),
        migrations.AddField(
            model_name='perfilrepartidor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_repartidor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddConstraint(
            model_name='asignacionpedido',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('repartidor',), name='unique_active_assignment_per_driver'),
        ),
    ]
